name: Push to main branch
'on': pull_request
env:
  NODE_OPTIONS: '--max_old_space_size=4096'
jobs:
  buildTest:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Test
        run: echo 'yarn test'
