name: v5 Branch - Push
'on': push
env:
  NODE_OPTIONS: '--max_old_space_size=4096'
jobs:
  buildTest:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/checkout@v2a
      - name: Build
        run: yarn build
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12
