name: Push to main branch
'on': push
env:
  NODE_OPTIONS: '--max_old_space_size=4096'
jobs:
  buildTestRelease:
    name: Build, test, release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build
        run: yarn build
      - name: Test
        run: echo 'yarn test'
      - name: Release
        run: echo 'yarn test'
